# Generated by Django 5.0.7 on 2024-07-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_productsize_size_product_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
