# Generated by Django 5.0.7 on 2024-07-22 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notification',
            field=models.CharField(default='Không thông báo', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_notifications', to='api.product'),
        ),
    ]
